config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from login_auth import views as auth_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/',auth_views.signup, name='signup'),
    path('summernote/', include('django_summernote.urls')),


]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path
from . import views
from .cb_views import TodoListView, TodoDetailView, TodoCreateView, TodoUpdateView, TodoDeleteView, CommentCreateView, \
    CommentUpdateView, CommentDeleteView

app_name = 'todo'
urlpatterns = [
    # path('', views.todo, name='todo'),
    # path('<int:todo_id>/', views.todo_info, name='todo_info'),
    # path('create/',views.todo_create, name='todo_create'),
    # path('<int:todo_id>/update', views.todo_update, name='todo_update'),
    # path('<int:todo_id>/delete', views.todo_delete, name='todo_delete'),

    path('', TodoListView.as_view(), name='list'),
    path('<int:todo_pk>/', TodoDetailView.as_view(), name='info'),
    path('create/',TodoCreateView.as_view(), name='create'),
    path('<int:pk>/update/', TodoUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', TodoDeleteView.as_view(), name='delete'),
    path('comment/create/<int:todo_pk>/',CommentCreateView.as_view(), name='comment_create'),
    path('comment/update/<int:pk>/',CommentUpdateView.as_view(), name='comment_update'),
    path('comment/delete/<int:pk>/',CommentDeleteView.as_view(), name='comment_delete'),
]

login_auth/models.py
from django.db import models

# Create your models here.

todo/models.py
from PIL import Image
from io import BytesIO
from pathlib import Path
from django.contrib.auth.models import User
from django.db import models
from django_extensions.db.models import TimeStampedModel
from django.urls import reverse

class Todo(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    start_date = models.DateField()
    end_date = models.DateField()
    is_completed=models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    image = models.ImageField('이미지', null=True, blank=True, upload_to='todo/%Y/%m/%d/')
    thumbnail = models.ImageField('썸네일', null=True, blank=True, upload_to='todo/%Y/%m/%d/thumbnail')

    def __str__(self):
        return self.title

    def get_absolute_url(self):

        return reverse('todo:info', kwargs={'todo_pk': self.pk})

    def get_thumbnail_url(self):
        if self.thumbnail:
            return self.thumbnail.url
        elif self.image:
            return self.image.url
        return None

    def save(self, *args, **kwargs):
        if not self.image:
            return super().save(*args, **kwargs)

        image = Image.open(self.image)
        image.thumbnail((300, 300))
        image_path = Path(self.image.name)

        thumbnail_name = image_path.stem
        thumbnail_extension = image_path.suffix.lower()
        thumbnail_filename = f'{thumbnail_name}_thumb{thumbnail_extension}'

        if thumbnail_extension in ['.jpg', '.jpeg']:
            file_type = 'JPEG'
        elif thumbnail_extension == '.gif':
            file_type = 'GIF'
        elif thumbnail_extension == '.png':
            file_type = 'PNG'
        else:
            return super().save(*args, **kwargs)

        temp_thumb = BytesIO()
        image.save(temp_thumb, file_type)
        temp_thumb.seek(0)
        self.thumbnail.save(thumbnail_filename, temp_thumb, save=False)
        temp_thumb.close()
        return super().save(*args, **kwargs)

class Comment(TimeStampedModel):
    todo = models.ForeignKey(Todo, on_delete=models.CASCADE,related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE,related_name='comments')
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return f'{self.todo.title} 댓글'
    class Meta:
        verbose_name='댓글'
        verbose_name_plural='댓글 목록'
        ordering=('created_at','-id')

todo/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget

from todo.models import Todo, Comment


class TodoForm(forms.ModelForm):

    class Meta:
        model=Todo
        fields=('title','description','image','start_date','end_date')
        widgets={
            'description':SummernoteWidget(),
        }

class TodoUpdateForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = ("title", "description","image","start_date", "end_date", "is_completed")


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('message',)
        widgets={
            'message':forms.Textarea(attrs={'class':'form-control','placeholder':'댓글을 작성하세요','rows':10,'cols':20}),
        }
        labels={
            'message':'내용'
        }

login_auth/views.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render,redirect
from django.conf import settings

def signup(request):
    form=UserCreationForm(request.POST or None)
    if form.is_valid():
        form.save()

        return redirect(settings.LOGIN_URL)

    context = {'form':form}
    return render(request,'registration/signup.html',context)

todo/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from django.core.paginator import Paginator
from .forms import TodoForm
from .models import Todo

def todo(request):
    todos=Todo.objects.all()
    q=request.GET.get('q')
    if q:
        todos=todos.filter(
            Q(title__icontains=q)|
            Q(description__icontains=q)|
            Q(author__username__icontains=q)
        )


    paginator=Paginator(todos,10)
    page=request.GET.get('page')
    page_object=paginator.get_page(page)

    context={'todos':todos
             ,'page_object':page_object}
    return render(request,'todo.html',context)
@login_required
def todo_info(request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id)
    context = {'todo': todo}
    return render(request, 'todo_info.html', context)
# Create your views here.

@login_required
def todo_create(request):
    form=TodoForm(request.POST or None)
    if form.is_valid():
        todo=form.save(commit=False)
        todo.author=request.user
        todo.save()

        return redirect(reverse('todo_info',kwargs={'todo_id':todo.id}))
    context={'form':form}
    return render(request,'todo_form.html',context)

@login_required
def todo_update(request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id,author=request.user)
    form=TodoForm(request.POST or None, instance=todo)
    if form.is_valid():
        todo=form.save()
        return redirect(reverse('todo_info',kwargs={'todo_id':todo.id}))
    context={'form':form}
    return render(request,'todo_form.html',context)

@login_required
@require_http_methods(['POST'])
def todo_delete(request, todo_id):
    todo = get_object_or_404(Todo,pk=todo_id)
    todo.delete()
    return redirect(reverse('todo'))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div style="text-align: right">
        {% if request.user.is_authenticated%}
            <form action="{% url 'logout' %}" method="POST">
                {% csrf_token %}
                <button>로그아웃</button>
            </form>
            <p>안녕하세요! {{ request.user.username }}님!</p>
        {% else %}
            <a href="{% url 'login' %}"><button>로그인</button></a>
            <a href="{% url 'signup' %}"><button>회원가입</button></a>
        {% endif %}
        
    </div>
{% block content %}{% endblock %}
</body>
</html>

templates/form_js.html
    <script>
        document.querySelectorAll('select, input,textarea').forEach(function (ele)){
            ele.classList.add('form-control');
        }
    </script>

templates/pagination.html
<div class="d-flex justify-content-center">
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if fragment%}#{{ fragment }}{% endif %}">&laquo;</a>
            </li><li class="page-item">
                   <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if fragment%}#{{ fragment }}{% endif %}">&LeftAngleBracket;</a>
            </li>
        {% endif %}

        {% if page_obj.number|add:-2 > 1 %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.number|add:-3 }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if fragment%}#{{ fragment }}{% endif %}">&hellip;</a>
            </li>
        {% endif %}

        {% for i in page_obj.paginator.page_range %}
            {% if page_obj.number == i %}
                <span>[현재 페이지]</span>
            {% elif i > page_obj.number|add:-3 and i < page_obj.number|add:3 %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ i }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if fragment%}#{{ fragment }}{% endif %}">{{ i }}</a>
                </li>
            {% endif %}
        {% endfor %}

        {% if page_obj.paginator.num_pages > page_obj.number|add:2 %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.number|add:3 }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if fragment%}#{{ fragment }}{% endif %}">&hellip;</a>
            </li>
        {% endif %}

        {% if page_obj.has_next %}
            <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if fragment%}#{{ fragment }}{% endif %}">
            &RightAngleBracket;
            </a>
            </li>
            <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if fragment%}#{{ fragment }}{% endif %}"> &raquo;</a>
            </li>
        {% endif %}
        </ul>
    </div>

templates/todo.html
{% extends 'base.html' %}
{% block content %}
    <h1>Todo List</h1>
    {% for todo in object_list %}
        <a href="{% url 'todo:info' todo.id %}">
            {{ todo.title }}</a><br>
    {% endfor %}
     <a href="{% url 'todo:create' %}"><button>글쓰기</button></a>
    <form method="get" class="my-3 d-flex">
    <input class="form-control-sm" name="q" type="text" placeholder="검색어를 입력하세요." value="{% if request.GET.q %}{{ request.GET.q }}{% endif %}">
    <button class="btn btn-sm btn-info ms-2">검색</button>
    </form>
    {% include 'pagination.html' %}
{% endblock %}

templates/todo_form.html
{% extends 'base.html' %}
{% block content %}
    <h1>TodoList {{ sub_title }}</h1>
    <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    
    <button>{{ btn_name }}</button>
    </form>
{% endblock %}
{% block js %}
{% include 'form_js.html' %}
{% endblock %}

templates/todo_info.html
{% extends 'base.html'%}
{% block content %}
    <h1>제목: {{ todo.title }}</h1>
    <h2>오늘의 할일: {{ todo.description | safe}}</h2>
        {% if todo.image %}
        <img src="{{ todo.image.url }}" alt="" class="row-cols-sm-6 col-8 w-100" >
    {% endif %}
    <p>시작날짜: {{ todo.start_date }}</p>
    <p>종료날짜: {{ todo.end_date }}</p>
    {% if todo.is_completed == 0%}
        <p>미완료</p>
    {% else %}
        <p>완료</p>
    {% endif %}
    작성자: {{ todo.author }}<br>
    {% if request.user == todo.author %}
        <div style="text-align: right">
            <a href="{% url 'todo:update' todo.id %}"><button>수정</button></a>
            <form action="{% url 'todo:delete' todo.id %}" method="POST" style="display:inline">
            {% csrf_token %}
            <button>삭제</button>
            </form>
        </div>
    {% endif %}


        <hr>
    {% if request.user.is_authenticated %}
        <form method="post" action="{% url 'todo:comment_create' todo.pk %}">
            {% csrf_token %}
            {{ comment_form.as_p }}
        <div class="text-end">
            <button class="btn btn-primary">등록</button>
        </div>
        </form>
    {% endif %}
    <div class="mb-2" id="comment_wrapper">
{% for comment in todo.comments.all %}
    <div class="comment" id="comment-{{ comment.pk }}">
        {% if form and comment.pk == form.instance.pk %}
            <form method="post" action="{% url 'todo:comment_update' comment.pk %}">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-sm btn-success">저장</button>
                <a href="{% url 'todo:info' todo_pk=todo.pk %}" class="btn btn-sm btn-secondary">취소</a>
            </form>
        {% else %}
            <p>{{ comment.message }}</p>
            <small>작성자: {{ comment.user.username }}, 작성일: {{ comment.created_at }}</small>
            {% if user == comment.user %}
                <a href="{% url 'todo:comment_update' comment.pk %}" class="btn btn-sm btn-primary">수정</a>
                <form method="post" action="{% url 'todo:comment_delete' comment.pk %}" style="display: inline;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('정말로 이 댓글을 삭제하시겠습니까?');">삭제</button>
                </form>
            {% endif %}
        {% endif %}
    </div>
{% endfor %}
    </div>

    {% include 'pagination.html' with fragment='comment_wrapper' %}
    <a href="{% url 'todo:list'%}" class="btn btn-sm btn-info">목록으로 돌아가기</a>

{% endblock %}

templates/user_detail.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>사용자 상세 정보</title>
</head>
<body>
    <h1>사용자 상세 정보</h1>
    <h2>사용자 ID: {{ user_id }}</h2>
    <ul>
        {% for key, value in user.items %}
            <li><strong>{{ key }}:</strong> {{ value }}</li>
        {% endfor %}
    </ul>
</body>
</html>

templates/users.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
  {% for user in user_db %}
      <a href="/users/{{ forloop.counter }}">{{ user }}번</a><br>
  {% endfor %}

</body>
</html>